#!/bin/bash

#David Rhoads, December 2019
#Script to delete old video files
#Replace /path/to/directory with actual path to video folder.
#Be sure folder is actually there before running the script
#-mtime checks the time since the last modification of the file
#-type -f tells the program it should look at files
#-delete tells the program to delete the files (surprise :-))

echo "This program deletes files older than a specified date at a specified location."
while true
do
    find '/path/to/directory' -mtime +30 -type f -delete
    sleep 30
done
