#!/bin/bash

#################################
# vetsim_copy_video_files       #
# Written by David Rhoads       #
# December 13, 2019             #
#################################

# https://github.com/kd2flz/OpenVetSimScripts 

#This script copies video files from a specified location to another specified location
#It can be set to continuously scan the folder for new files
#I would reccomend installing grsync (sudo apt install grsync), and using it's built in dry run feature to generate the correct script
#However, if you feel confident, you can also modify the below script to reflect the correct paths for your device

echo "This program copies files from a specified folder on your hard drive to an external device."
while true
    do
       rsync -r -t -v --progress --ignore-existing --modify-window=1 -z -s /home/david/Pictures /'media/david/Dave Rhoads/Pictures'
        #Change the number after sleep to reflect the number of seconds you want the script to wait before running rsync again
        sleep 10
    done